"""users and confidence_reasons

Revision ID: a1c4d2f80b31
Revises: b9342906a5a6
Create Date: 2026-07-28 21:31:01.310133

Three additions for the review API (P4.T3):

* ``users`` -- the accounts that can sign in to the review service, so
  ``corrections.corrected_by`` can eventually name a real account instead of a
  shared key. ``role`` is a plain ``String(16)``, not a database ENUM: the
  migration drift guard (``tests/test_migrations.py``) runs on SQLite only and
  cannot see a new ENUM member, so an ENUM here would pass locally and fail on
  Postgres. Role validation lives in ``receipts.persist.users``, next to the
  role constants the API guards use.
* ``receipts.confidence_reasons`` -- the ``(reason, penalty)`` pairs that
  produced ``confidence``, persisted next to it so the review UI can show a
  reviewer why a receipt scored what it did. Nullable on purpose: NULL means
  "not recorded" (a row written before this column existed, or a run that
  failed before scoring), while ``[]`` means "nothing lowered the score".
* ``validation_findings.created_at`` -- not part of the original spec §6.5
  table. Added so ``get_findings`` (P4.T3) can return findings in the order
  they were written; without a timestamp there is nothing to order by besides
  the random-UUID primary key, which is not write order.

Autogenerated from ``receipts.persist.models`` and then hand-tidied for
portability, matching ``b9342906a5a6``'s conventions.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1c4d2f80b31"
down_revision: str | Sequence[str] | None = "b9342906a5a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _jsonb() -> sa.types.TypeEngine[Any]:
    """A JSON column that is ``JSONB`` on Postgres and ``JSON`` on SQLite."""
    return sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


def upgrade() -> None:
    """Add ``users``, ``receipts.confidence_reasons``, and ``validation_findings.created_at``."""
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("confidence_reasons", _jsonb(), nullable=True))

    with op.batch_alter_table("validation_findings", schema=None) as batch_op:
        # No server_default: the ORM populates this with a Python-side default
        # (see receipts.persist.models.ValidationFinding) so rows written in the
        # same transaction still get distinct, write-ordered timestamps -- a
        # server-side now() ties for every row in one transaction on Postgres,
        # and SQLite's CURRENT_TIMESTAMP only has whole-second resolution.
        batch_op.add_column(sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))


def downgrade() -> None:
    """Drop everything this revision added, in reverse order."""
    with op.batch_alter_table("validation_findings", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.drop_column("confidence_reasons")

    op.drop_table("users")
