"""create seven-table receipt schema

Revision ID: b9342906a5a6
Revises:
Create Date: 2026-07-28 09:47:35.172430

The initial schema for spec §6: ``merchants``, ``receipts``, ``line_items``,
``extraction_runs``, ``validation_findings``, ``corrections``, ``review_tasks``.
Autogenerated from ``receipts.persist.models`` and then hand-tidied for
portability; a test asserts this revision and the ORM metadata stay identical.

Portability (ADR-0004) -- the same revision applies to Postgres and SQLite:

* ids are ``sa.Uuid`` (native ``UUID`` on Postgres, ``CHAR(32)`` on SQLite);
* document columns are ``JSON`` with a ``JSONB`` variant for Postgres;
* timestamps are ``DateTime(timezone=True)`` defaulting to ``sa.func.now()``,
  which compiles to ``now()`` on Postgres and ``CURRENT_TIMESTAMP`` on SQLite;
* every monetary column is ``Numeric``, never ``Float`` (ADR-0001).
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9342906a5a6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Native ``ENUM`` types Postgres creates alongside the tables. SQLite renders
#: them as ``VARCHAR``, so it has nothing to clean up on downgrade.
ENUM_TYPE_NAMES = (
    "legibility",
    "receipt_status",
    "pass_name",
    "finding_severity",
    "review_state",
)


def _jsonb() -> sa.types.TypeEngine[Any]:
    """A JSON column that is ``JSONB`` on Postgres and ``JSON`` on SQLite."""
    return sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


def upgrade() -> None:
    """Create the seven tables, their constraints, and the receipts indexes."""
    op.create_table(
        "merchants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("tax_id", sa.Text(), nullable=True),
        sa.Column("name_variants", _jsonb(), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("default_currency", sa.String(length=3), nullable=True),
        sa.Column("hints", _jsonb(), nullable=False),
        sa.Column("receipt_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "receipts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=True),
        sa.Column("merchant_name_raw", sa.Text(), nullable=True),
        sa.Column("receipt_number", sa.Text(), nullable=True),
        sa.Column("txn_date", sa.Date(), nullable=True),
        sa.Column("txn_time", sa.Time(), nullable=True),
        sa.Column("date_raw", sa.Text(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("subtotal", sa.Numeric(14, 4, asdecimal=True), nullable=True),
        sa.Column("tax_total", sa.Numeric(14, 4, asdecimal=True), nullable=True),
        sa.Column("discount_total", sa.Numeric(14, 4, asdecimal=True), nullable=True),
        sa.Column("total", sa.Numeric(14, 4, asdecimal=True), nullable=True),
        sa.Column("tender_amount", sa.Numeric(14, 4, asdecimal=True), nullable=True),
        sa.Column("change_amount", sa.Numeric(14, 4, asdecimal=True), nullable=True),
        sa.Column("payment_method", sa.Text(), nullable=True),
        sa.Column("card_last4", sa.String(length=4), nullable=True),
        sa.Column("is_handwritten", sa.Boolean(), nullable=False),
        sa.Column(
            "legibility",
            sa.Enum("good", "fair", "poor", "unreadable", name="legibility"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(4, 3, asdecimal=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "auto_approved",
                "needs_review",
                "reviewed",
                "rejected",
                name="receipt_status",
            ),
            nullable=False,
        ),
        sa.Column("image_key", sa.Text(), nullable=False),
        sa.Column("processed_image_key", sa.Text(), nullable=True),
        sa.Column("image_phash", sa.String(length=16), nullable=False),
        sa.Column("duplicate_of", sa.Uuid(), nullable=True),
        sa.Column("receipt_is_inconsistent", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        # Self-FK: a receipt flagged as a duplicate points at the original.
        sa.ForeignKeyConstraint(["duplicate_of"], ["receipts.id"]),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_receipts_image_phash", "receipts", ["image_phash"], unique=False)
    op.create_index(
        "ix_receipts_merchant_id_txn_date",
        "receipts",
        ["merchant_id", "txn_date"],
        unique=False,
    )
    op.create_index(
        "ix_receipts_merchant_id_txn_date_total",
        "receipts",
        ["merchant_id", "txn_date", "total"],
        unique=False,
    )
    op.create_index("ix_receipts_status", "receipts", ["status"], unique=False)
    op.create_table(
        "corrections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("field_path", sa.Text(), nullable=False),
        sa.Column("value_before", sa.Text(), nullable=True),
        sa.Column("value_after", sa.Text(), nullable=True),
        sa.Column("corrected_by", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "extraction_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column(
            "pass_name",
            sa.Enum("triage", "extract", "repair", "consistency", name="pass_name"),
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column("prompt_hash", sa.String(length=16), nullable=False),
        sa.Column("raw_response", _jsonb(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(10, 6, asdecimal=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "line_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("description_raw", sa.Text(), nullable=False),
        sa.Column("sku", sa.Text(), nullable=True),
        sa.Column("qty", sa.Numeric(12, 4, asdecimal=True), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("unit_price", sa.Numeric(14, 4, asdecimal=True), nullable=True),
        sa.Column("line_total", sa.Numeric(14, 4, asdecimal=True), nullable=True),
        sa.Column("modifiers", _jsonb(), nullable=False),
        sa.Column("bbox", _jsonb(), nullable=True),
        sa.Column("line_confidence", sa.Numeric(4, 3, asdecimal=True), nullable=False),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("receipt_id", "position", name="uq_line_items_receipt_position"),
    )
    op.create_table(
        "review_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("assigned_to", sa.Text(), nullable=True),
        sa.Column(
            "state",
            sa.Enum("open", "in_progress", "done", name="review_state"),
            nullable=False,
        ),
        sa.Column(
            "opened_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        # One open review task per receipt, enforced by the database.
        sa.UniqueConstraint("receipt_id"),
    )
    op.create_table(
        "validation_findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("error", "warn", "info", name="finding_severity"),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("context", _jsonb(), nullable=False),
        sa.Column("resolved_by_repair", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    """Drop everything this revision created, children before parents."""
    op.drop_table("validation_findings")
    op.drop_table("review_tasks")
    op.drop_table("line_items")
    op.drop_table("extraction_runs")
    op.drop_table("corrections")
    op.drop_index("ix_receipts_status", table_name="receipts")
    op.drop_index("ix_receipts_merchant_id_txn_date_total", table_name="receipts")
    op.drop_index("ix_receipts_merchant_id_txn_date", table_name="receipts")
    op.drop_index("ix_receipts_image_phash", table_name="receipts")
    op.drop_table("receipts")
    op.drop_table("merchants")

    # Postgres keeps the native ENUM types after their tables are gone, which
    # would make a re-upgrade fail with "type already exists"; SQLite has no
    # types to drop.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for type_name in ENUM_TYPE_NAMES:
            op.execute(f"DROP TYPE IF EXISTS {type_name}")
