"""tax bands and the tax-inclusive convention

Revision ID: d5b8c31e7a04
Revises: c7f1a9e4d208
Create Date: 2026-08-25 22:41:18.402711

Two additions, both closing the same gap: the extractor reads a receipt's tax
breakdown and the database had nowhere to put it.

* ``tax_bands`` -- one row per printed band of the tax breakdown: the VATABLE
  SALES / VAT-EXEMPT SALES / zero-rated block a Philippine BIR sales invoice
  prints beneath its items grid. Mirrors ``line_items``: a positioned child of
  ``receipts``, ``ON DELETE CASCADE``, unique on ``(receipt_id, position)``.
* ``receipts.prices_include_tax`` -- whether the line-item amounts already
  include tax, **as the document states it**. R020 and R024 read it to decide
  which figure the lines should sum to. Nullable, because the ordinary case is
  a receipt that does not say, and a guess would be indistinguishable from a
  reading.

**A child table rather than a JSONB column, and the reason is correctability.**
``line_items.modifiers`` and ``line_items.bbox`` are JSONB and are deliberately
absent from ``_LINE_ITEM_FIELDS`` -- "they are documents, not scalars".
``extract/paths.py`` already documents ``totals.tax_breakdown[0].amount`` as
valid correction grammar, and a reviewer has to be able to fix a misread band,
so every figure needs to be addressable on its own. JSONB would put those paths
out of reach by exactly the reasoning that keeps ``modifiers`` out.

**The bands are also arithmetic.** R-rules reconcile ``sum(band.amount)``
against ``totals.tax``, and a band is the only independent check on a misread
total. Measured on this project's own data: a model returned ``total = 2.0000``
for a receipt printing 2,000, on a page that also printed ``Amount: Net of VAT
1785.71`` and ``Add: VAT 214.29`` -- which sum to exactly 2,000. A rule can make
that comparison only if the bands are scalars it can reach.

**THERE IS NO BACKFILL, AND NONE IS POSSIBLE.** Not a decision -- the data never
existed to migrate. ``tax_breakdown`` and ``prices_include_tax`` were extracted
on every run and then discarded at persistence, because no column held them;
``review/serializers.py`` recorded exactly that under "Lossy against the full
extraction schema". So after this revision every EXISTING receipt has zero
bands and a NULL convention, and that is the truthful state rather than a bug.
Only receipts extracted after this lands will carry them. Anyone who wants
bands on an old receipt has to re-run extraction on it.

``rate`` is ``Numeric(7, 4)`` and not the ``Numeric(4, 3)`` used for ratios
elsewhere. The upstream convention is unstated -- ``TaxBand.rate`` carries no
description and the prompt asks only for "rate bands" -- so a 12% band may
arrive as ``12`` or as ``0.12``. ``Numeric(4, 3)`` overflows on ``12``. Nothing
computes from the column, so it stores what was printed rather than imposing a
convention the document did not state.

Hand-written rather than autogenerated, matching ``b9342906a5a6``'s conventions:
``sa.Numeric(14, 4)`` for money, an explicit ``ForeignKey`` with
``ondelete="CASCADE"``, and a named ``UniqueConstraint`` so the constraint can
be dropped by name on either backend (ADR-0004).

**No standalone index on ``receipt_id``**, and that is deliberate rather than an
omission. The first draft created one; ``test_migration_schema_matches_orm_metadata``
failed it as drift, because the ORM declares none -- and it was right twice
over. ``line_items``, whose access pattern is identical, has no such index
either, and ``uq_tax_bands_receipt_position`` already indexes ``receipt_id`` as
its leading column on both backends.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5b8c31e7a04"
down_revision: str | Sequence[str] | None = "c7f1a9e4d208"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create ``tax_bands`` and add ``receipts.prices_include_tax``."""
    op.create_table(
        "tax_bands",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("base", sa.Numeric(14, 4), nullable=True),
        sa.Column("rate", sa.Numeric(7, 4), nullable=True),
        sa.Column("amount", sa.Numeric(14, 4), nullable=True),
        sa.ForeignKeyConstraint(
            ["receipt_id"], ["receipts.id"], name="fk_tax_bands_receipt_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_tax_bands"),
        sa.UniqueConstraint("receipt_id", "position", name="uq_tax_bands_receipt_position"),
    )
    # Nullable with no server_default: unlike `is_template_row` in
    # `f3ae0f86e0e6`, there is nothing this column could be backfilled WITH. A
    # `false` default would assert that every existing receipt printed
    # tax-exclusive amounts, which is a claim about paper nobody has read.
    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prices_include_tax", sa.Boolean(), nullable=True))


def downgrade() -> None:
    """Drop what this revision added, in reverse order.

    **This destroys every correction a reviewer has made to a tax band**, and
    the upgrade cannot put them back -- see the no-backfill note above. It is
    reversible in the schema sense and lossy in the data sense.
    """
    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.drop_column("prices_include_tax")

    op.drop_table("tax_bands")
