"""buyer and template rows

Revision ID: f3ae0f86e0e6
Revises: a1c4d2f80b31
Create Date: 2026-08-18 15:37:07.952489

Three additions for buyer capture and blank-row transcription:

* ``receipts.buyer_name_raw`` / ``receipts.buyer_tax_id`` -- who the receipt was
  issued TO, the "Sold To" / "Registered Name" block, mirroring
  ``receipts.extract.schema.Buyer``. Distinct from the merchant columns, which
  are who *issued* it: a BIR sales invoice carries both names and both TINs and
  they are different numbers. Both nullable, deliberately -- most receipts name
  no buyer at all and every receipt in the golden set leaves the buyer TIN
  blank, so ``NOT NULL`` would turn an ordinary receipt into a persist-stage
  failure. There is no ``buyer_address``: the forms print a Business Address
  line for the buyer and it is blank throughout the golden set.
* ``line_items.is_template_row`` -- a pre-printed product row left blank on the
  form, transcribed so nothing on the paper is lost but flagged as NOT a
  purchase, so the arithmetic and line-item-quality rules can skip it. Added
  ``NOT NULL`` with a ``server_default`` of ``false``: both SQLite and Postgres
  refuse ``ADD COLUMN ... NOT NULL`` with no default the moment the table holds
  a row (there is nothing to backfill existing rows with), and ``line_items``
  gets a row per line of every processed receipt. The server-side default only
  backfills; going forward the ORM's Python-side default supplies ``False`` for
  every row it writes (see ``receipts.persist.models.LineItem``).

Autogenerated from ``receipts.persist.models`` and then hand-tidied for
portability, matching ``b9342906a5a6``'s conventions.

Portability note (ADR-0004) -- the one edit that matters. Autogenerate ran
against SQLite and rendered the boolean default as ``sa.text("0")``, which is
SQLite's spelling of ``false`` frozen into the migration. That is not portable:
Postgres rejects an integer default on a ``BOOLEAN`` column ("column ... is of
type boolean but default expression is of type integer"), so the revision would
apply here and fail in production. ``sa.false()`` is the portable form -- it
compiles to ``0`` on SQLite and ``false`` on Postgres -- and it matches the
``server_default`` on the ORM model, which is what keeps the drift guard honest.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3ae0f86e0e6"
down_revision: str | Sequence[str] | None = "a1c4d2f80b31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add ``line_items.is_template_row`` and the two ``receipts`` buyer columns."""
    with op.batch_alter_table("line_items", schema=None) as batch_op:
        # server_default=sa.false(), not sa.text("0"): see the portability note
        # in the module docstring. It is also required rather than optional --
        # ADD COLUMN ... NOT NULL with no default fails on both backends once
        # the table holds a row.
        batch_op.add_column(
            sa.Column(
                "is_template_row",
                sa.Boolean(),
                server_default=sa.false(),
                nullable=False,
            )
        )

    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("buyer_name_raw", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("buyer_tax_id", sa.Text(), nullable=True))


def downgrade() -> None:
    """Drop the three columns this revision added, in reverse order."""
    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.drop_column("buyer_tax_id")
        batch_op.drop_column("buyer_name_raw")

    with op.batch_alter_table("line_items", schema=None) as batch_op:
        batch_op.drop_column("is_template_row")
